# -*- coding: utf-8 -*-
"""bitcoin mail gönderme

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qO1Hp8_0NA0n2WOMDdMytoqgTYiZVWo0
"""

import cryptocompare
import smtplib
from email.mime.text import MIMEText

def kur_getir():
    deger = cryptocompare.get_price('BTC', currency='USD')['BTC']['USD']
    return deger

def mail_gonder(konu, body):

    gonderici_mail = "your_email@gmail.com"
    alici_mail = "recipient_email@gmail.com"   # E-posta gönderime ayarları
    sifre = "your_email_password"


    mesaj = MIMEText(body)
    mesaj["Subject"] = konu
    mesaj["From"] = gonderici_mail          # E-posta oluşturma
    mesaj["To"] = alici_mail


    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()
        server.login(gonderici_mail, sifre)          # SMTP sunucusuna bağlanma ve e-posta gönderme
        server.sendmail(gonderici_mail, alici_mail, mesaj.as_string())

def main():
    alt_deger = float(input("Alt  değerini giriniz: "))
    ust_deger = float(input("Üst  değerini giriniz: "))

    while True:
        normal_deger = kur_getir()

        if normal_deger < alt_deger or normal_deger > ust_deger:
            konu = "Bitcoin Kuru Uyarısı"
            body = f"Bitcoin (BTC) kurunuza dair değer aşıldı! Güncel kur: {normal_deger} USD"
            mail_gonder(konu, body)
            print("E-posta gönderildi!")

if __name__ == "__main__":
    main()